---
# Handler to handle control plane notifications.

- name: Apply Netplan
  become: true
  ansible.builtin.command: netplan apply
  async: 45
  poll: 0
  tags: netplan

- name: Restart containerd
  become: true
  ansible.builtin.systemd_service:
    name: containerd
    daemon_reload: true
    state: restarted
  tags: containerd

- name: Restart kubelet
  become: true
  ansible.builtin.systemd_service:
    name: kubelet
    daemon_reload: true
    state: restarted
  tags: kubernetes

- name: Restart etcd
  become: true
  ansible.builtin.systemd_service:
    name: etcd
    daemon_reload: true
    state: restarted
  tags: etcd

- name: Restart kube-apiserver
  become: true
  ansible.builtin.systemd_service:
    name: kube-apiserver
    daemon_reload: true
    state: restarted
  tags: kubernetes

- name: Restart kube-scheduler
  become: true
  ansible.builtin.systemd_service:
    name: kube-scheduler
    daemon_reload: true
    state: restarted
  tags: kubernetes
