---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    nfs:
      server: 192.168.50.2
      path: /volume1/kubernetes
    storageClass:
      defaultClass: true
      name: nfs-client
    # RPi 5 is ARM64, ensuring we pull the correct image if needed,
    # though standard helm chart usually handles multi-arch.
