---
# Handler to handle K8s node notifications.

- name: Restart containerd
  become: true
  ansible.builtin.systemd_service:
    name: containerd
    daemon_reload: true
    state: restarted
  tags: containerd

- name: Restart kubelet
  become: true
  ansible.builtin.systemd_service:
    name: kubelet
    daemon_reload: true
    state: restarted
  tags: kubernetes