---
# This playbook deploys the server configuration stack to all relevant nodes in this site.

- name: Apply the common configuration to all nodes
  hosts: all, !local
  remote_user: gawbul
  roles:
    - common

- name: Setup K3s on all nodes
  hosts: [k8s_control_planes, k8s_worker_nodes]
  remote_user: gawbul
  roles:
    - k3s

- name: Bootstrap the cluster with the relevant configuration
  hosts: local
  remote_user: gawbul
  roles:
    - local
